### ISSUE TITLE
HTTP -> HTTPS redirection is faulty on shadered.org

### ISSUE THREAD

**Issue by Calinou** [dfranx/SHADERed#136]
When you visit <http://shadered.org>, you get a 403 Forbidden error. However, [https://shadered.org/](https://shadered.org) works fine. This hints at an issue in the web server configuration.

PS: You should also make `https://www.shadered.org` redirect to `https://shadered.org` (rather than serving the same pages under both subdomains) to avoid potential issues with duplicate content in search engines.

See also https://github.com/dfranx/THEMEed/issues/1.

**Comment by dfranx** [comment]
Thank you for reporting this. Both http://shadered.org and www.shadered.org should now redirect to https://shadered.org . Though, now I have a problem with `api.shadered.org` subdomain (which SHADERed app uses to communicate with the web server). It serves content from `shadered.org` instead of `shadered.org/api`. I'll leave this open until I fix that issue.

**Comment by dfranx** [comment]
Should be completely working now!
