### ISSUE TITLE
Can't get rid of "'descriptor set': only allowed when using GLSL for Vulkan" error

### ISSUE THREAD

**Issue by expenses** [dfranx/SHADERed#168]
Hi, I've done the following things:

1. Compiled SHADERed version commit https://github.com/dfranx/SHADERed/commit/610f2ac36c5d93aae6df5628158089cddfa289ec.
2. Set up vertex and fragment shaders with a `.vk` extension.
3. Created a new shader pass with the `Language` set to `Vulkan GLSL` and loaded the shaders.

![1610232997](https://user-images.githubusercontent.com/13566135/104110272-7b4c2980-52d6-11eb-99b8-f1378951809b.png)
 
Is there something obvious I'm doing wrong? SHADERed seems awesome, and I'm frustratingly close to being able to use it 😅

**Comment by dfranx** [comment]
Hello! Thanks for reporting this. I think the cause of this problem is the same as this one: https://github.com/dfranx/SHADERed/issues/138 . Full "GLSL for Vulkan" isn't currently supported as SHADERed uses OpenGL for rendering. Though, I might implement a Vulkan renderer backend in the future which would fix this issue.
So, to answer your question, you are not doing anything wrong, its SHADERed's fault 😅
You could use OpenGL version of GLSL or you could just remove the "set = 1" part of your code (AFAIK `binding` is supported in normal GLSL).
