### ISSUE TITLE
The preview window becomes black (empty/blank) and weird. (HLSL)

### ISSUE THREAD

**Issue by lyhyl** [dfranx/SHADERed#199]
![image](https://user-images.githubusercontent.com/3370369/116287373-e86ec680-a7c2-11eb-9a2e-ba9cfc51efbb.png)
![image](https://user-images.githubusercontent.com/3370369/116287451-02a8a480-a7c3-11eb-886a-be9cd3634ece.png)
As the pixel inspect window shown, the pixel's color is not black, but the preview window is blank.

But the below one works as expected:
![image](https://user-images.githubusercontent.com/3370369/116287324-d9881400-a7c2-11eb-8f2b-12db0e86bbc7.png)

other details:
HLSL Project
![image](https://user-images.githubusercontent.com/3370369/116287858-7945a200-a7c3-11eb-8556-ec2bd6e221bc.png)

**Comment by dfranx** [comment]
Sorry for slow response.
This could be caused by two things:
1. There was some form of a bug in SHADERed with HLSL shaders that would happen when one of the textures were not used and so it was optimized out of the code; the bindings would be shifted and the wrong texture would be sampled. Haven't found a solution for this one. Though, as seen in your screenshots, you are using both tex0 and tex1 so I believe this shouldn't happen in your case.
2. Either something was not bound properly by SHADERed or there's some shader code error.

I'd need the project files in order to tackle this issue.

**Comment by lyhyl** [comment]
hmmm, I can confirm that it is caused by a large array (the `data`).
I have deleted the original project, but reproduced it on version 1.5.3.
When the data contains only 40 elements, everything works fine.
![image](https://user-images.githubusercontent.com/3370369/124360436-64bad580-dc5c-11eb-85a2-c90c44405104.png)
When the length increases to 4096, we will get the weird result without any compiling error or warning.
![image](https://user-images.githubusercontent.com/3370369/124360526-fb879200-dc5c-11eb-9062-e3f7e85ae566.png)
When the length increases to 409600, the Shadered will crashed directly.

**Comment by dfranx** [comment]
Not sure if it's even allowed to define such big arrays. That's why there are buffers -- use a buffer object in your project.
This is not a bug on my end. Thanks for reporting however!
