### ISSUE TITLE
Crash on certain shader inputs

### ISSUE THREAD

**Issue by CptPotato** [dfranx/SHADERed#20]
I recently updated my version of shadered (I think I skipped 2 or 3 releases) and can't open one of my projects anymore. It seems like the shader input layout is giving it trouble (alignment issue?) but the log output doesn't hint at anything specific.

You can reproduce it by using this input layout (hlsl):
```hlsl
cbuffer cbPerFrame : register(b0)
{
	float4x4 matGeo;
	float4x4 matVP;
	float4x4 matGeoLast;
	float4x4 matVPLast;
	int frame;
	float2 viewport;
	float4x4 matVInv;
};
```

**Comment by dfranx** [comment]
Your cbuffer definitely causes the crash. An exception: "Buffer block cannot be expressed as any of std430, std140, scalar, even with enhanced layouts. You can try flattening this block to support a more flexible layout." is thrown.

It works fine when it is reordered in this way (or just float2 before int):
```hlsl
cbuffer cbPerFrame : register(b0)
{
	float4x4 matGeo;
	float4x4 matVP;
	float4x4 matGeoLast;
	float4x4 matVPLast;
	float4x4 matVInv;
	float2 viewport;
	int frame;
};
```

I guess I could encapsulate this in a try-catch block just to prevent crashes. I don't think I can fix it.

Also a quick note: since HLSL is being translated to GLSL, the actual order of variables doesn't matter (like it usually does when using Direct3D). Only the names inside of the cbuffer matter. So you can just reorder variables and it should keep working as expected.

**Comment by CptPotato** [comment]
Thanks, this solved the issue for me.

**Comment by dfranx** [comment]
It shouldn't crash anymore.
