### ISSUE TITLE
Support for Vulkan GLSL syntax

### ISSUE THREAD

**Issue by cdgiessen** [dfranx/SHADERed#21]
In vulkan, shader inputs have to have a `location(set = X, binding = Y) uniform ...` to specify where everything is. Currently SHADERed simply ignores these and doesn't let you use them in variables.

It would be very handy to be able to use this program for shader dev, but right now I have to modify my shaders so much its hard to justify.

It shouldn't be too big of a change, vulkan glsl isn't that different. It just has additional requirements that opengl doesn't.

**Comment by dfranx** [comment]
Do you mean the [layout qualifier](https://www.khronos.org/opengl/wiki/Layout_Qualifier_(GLSL))? I don't think I can do it for the uniform input variables. Their value is currently set using their name so the layout qualifier is ignored. I think I can do it for the samplers though (if that's what you wanted). 
Also, the layout qualifier shouldn't be ignored (and should work) for buffers and images.

**Comment by cdgiessen** [comment]
Yes, in vulkan the set and binding layout qualifer is added, which currently makes a shader fail to compile. 
When I made the issue, it was after quickly playing around and misspoke about layout qualifiers being ignored.  

Samplers should work well, since each samplers is usually bound to an individual "binding" slot.
What wouldn't be easy is struct bindings, where a struct is bound with a specific name, and access is done through that name. Much of my stuff uses this syntax, and I'm not sure how it would work with your program.
```glsl
layout (set = 1, binding = 0) uniform Light
{
	vec3 position;
	vec3 color;
        float intensity
} light;
...
vec3 outColor = light.color * mat_color;
```

I wouldn't mind if some of the features didn't work, I just would like to be able to compile them with vulkan syntax. glslang and spirv-cross both should have flags that enable the vulkan syntax paths.

This isn't a small request so I would totally understand not trying to support every api and shader language under the sun.

**Comment by dfranx** [comment]
Actually I did some tests, and this is totally doable and isn't that much of a big request. I think it shouldn't take too much time.

Although the `layout` part will be ignored but I don't think that is much of a problem (you can leave it in the shader and 'pretend' that it works and once you move the code to your engine/whatever it will actually do something - if that makes sense). The variables will have to be set using the names such as "light.color" in the variable manager.

Do you think that this solution is good? Any suggestions? In my opinion it sounds good. It would work just like HLSL shaders (the "register(bX)" part when declaring constant buffers actually doesn't do anything and is ignored).

**Comment by cdgiessen** [comment]
That sounds fine to me! Ignoring the layout stuff is just fine and being able to access struct members just by having a dot would be ideal.

I'd be happy to help out if there is anything I can do.

**Comment by dfranx** [comment]
Implemented!

Thanks for offering to help! Well... do you have some Vulkan shaders to test this new SHADERed feature?

Also, since the regular GLSL shaders don't go throught glslang & SPIRV-Cross, which means faster compilation, I wanted it to stay that way. So you actually have to set the proper filename extension for Vulkan GLSL shaders in settings (in the General tab) for them to be detected. If you want to you can even add the ".glsl" filename extension (although, all the examples won't work then because of the missing layout qualifiers).

**Comment by cdgiessen** [comment]
Wow, you work fast!
https://github.com/cdgiessen/VulkanRenderer/tree/master/assets/shaders

Thats my in progress engine, though I wouldn't say they are amazing by any stretch. The shaders also make use of `#include` for code reuse, and I haven't checked if your work supports that too.

**Comment by dfranx** [comment]
Thanks!

I've tried the gameObject shaders but I can't get them to work. The shaders compile and all the uniforms are set but the pointLightContrib and spotLightContrib values are all 0s so there is no output.

I don't know if I am doing something wrong or if there is currently a bug in SHADERed. I will test it more when I get on Linux.

I think that the #include should be supported in the HLSL and Vulkan GLSL shaders (since they go through glslang). But I actually tested it and for some reason they don't work. Although, I wonder if I should even add #include to SHADERed since they are not, as far as I know, in the GLSL/HLSL specification/standard.

**Comment by cdgiessen** [comment]
gameObject is something I need to fix up (as is most everything in that repo unfortunately)
I can test it myself after work. 

#include would be super handy. I'm pretty sure its common in hlsl, but I do know its a glsl extension (not core). Not supporting it is okay though, its not a trivial features since to get it to work you'd need a way to specify the "include" directories. For me, glslang makes it pretty easy since I control where everything goes but your case not so much.

**Comment by dfranx** [comment]
I mean, if you have time it would be great. But you have to compile SHADERed since the binaries are not out yet.

I have no idea why it is not rendering anything. Here is my project:
[vktest.zip](https://github.com/dfranx/SHADERed/files/3644136/vktest.zip)

Maybe uniforms cant have structures inside of structures - so maybe directional.lights[0].direction name is invalid?
Behind the scenes I transform all the UBOs into uniform structures, so instead of:
```glsl
layout (...) uniform DirectionalLights {
    DirectionalLight lights[...];
} directional;
```
it is:
```glsl
uniform struct DirectionalLights {
    DirectionalLight lights[...];
} directional;
```
Sorry for asking weird questions, haven't used GLSL too much.

As for the #includes, sure, I will implement them one day but not right now.
