### ISSUE TITLE
render output filenames should be left padded

### ISSUE THREAD

**Issue by Nine-H** [dfranx/SHADERed#220]
I rendered a shader out to a series of frames, and it worked fine, except when I tried to import the frames into my nle (kdenlive) as an image sequence, they're loaded out of order because the frame numbers are not left padded.

I would like left padded numbers in rendered frame filenames to facilitate using shadered for multimedia.

Cheers and this is otherwise great software.

edit: I was going to write a patch, and when I read the source code I realised that I could put sprintf tokens in the filename to set the padding how I wanted. Maybe this should be more discoverable but I got my render in the end. Let me know if you'd accept a patch to automatically leftpad the frame number if no format is found and I can knock it out for you, cheers.

**Comment by dfranx** [comment]
Hey!
Sorry for the slow response, but yeah, you can put sprintf specifiers in the filename to add the padding (mentioned in the documentation, I believe).
But I've made it now so that it by default adds left padding (based on the number of frames being exported).
Thank you for nice words and for the feedback, I love getting feedback on QoL stuff like this.
