### ISSUE TITLE
Instancing not exposed for arbitrary vertex buffers

### ISSUE THREAD

**Issue by Cazadorro** [dfranx/SHADERed#226]
Instancing should be exposed for arbitrary vertex buffers.  I don't quite understand why it isn't (isn't it more difficult to restrict this part of the SHADERed interface than to keep it the same?), but the interface between vertex buffers and pre-defined geometry aught to be the same.   Instancing should still be exposed when no backing buffer is selected, hopefully along side [buffer-less vertex rendering](https://github.com/dfranx/SHADERed/issues/221), where the vertex count should also be able to be independently selected.

**Comment by dfranx** [comment]
Thanks for reporting.
I haven't restricted instancing for vertex buffers objects it's just that I had to manually implement it (both in the property UI and in the rendering code) because `'Geometry'` and `'VertexBuffer'` objects act different (& have a different underlying code).
Anyway, `'VertexBuffer'` objects can now be instanced:
![image](https://user-images.githubusercontent.com/30801537/124363091-85256880-dc39-11eb-8a84-708d1c6067ec.png)
