### ISSUE TITLE
SHADERed fails to start after being installed system-wide on Linux

### ISSUE THREAD

**Issue by Calinou** [dfranx/SHADERed#38]
When starting SHADERed from the system-wide installed binary, I get the following error message:

```text
terminate called after throwing an instance of 'ghc::filesystem::filesystem_error'
  what():  No such file or directory: './plugins/'
[1]    23821 abort (core dumped)  shadered
```

This doesn't occur if running the `SHADERed` binary in the `bin/` folder.
This seems to be a known issue judging by [this file](https://github.com/Calinou/SHADERed/blob/e6f700e3661db3523471cca1246c6c9dbe940d67/Objects/PluginAPI/PluginManager.cpp#L34), but I thought it'd be a good idea create an issue for reference :slightly_smiling_face:

**Comment by dfranx** [comment]
@Calinou thanks for reporting! Should be fixed now! I forgot to add `plugins` directory to the cmake's install() command. Nevertheless, it shouldn't crash just because there is no `plugins` directory so I've also added a simple check to see if it exists.

That comment was referencing logs - I had no idea it crashed after being installed so thank you once again :smiley: .
