### ISSUE TITLE
[feature request] ShaderToy Mode

### ISSUE THREAD

**Issue by Kashouryo** [dfranx/SHADERed#40]
This project is really impressive! I always want to find a real-time shader testing software, and here I found it!

I hope this software can have a ShaderToy Mode that can run ShaderToy codes directly in the software without tweaking. It will be beneficial to the user if the shader is too laggy in the browser or if the user simply wants to play around with the shader locally.

Thank you for bringing us this awesome shader software!

**Comment by dfranx** [comment]
@Kashouryo Thank you for the kind words! I am glad you like this piece of software.
I actually plan to do this but in form of a plugin. I will add button `Import from ShaderToy` in the `File` menu which will ask the user for ShaderToy link. It will then do all the tweaking and set up a proper SHADERed project.
Thanks to ShaderToy's API this shouldn't be too difficult to implement and shouldn't take more than few days to implement.
Thoughts?

**Comment by Kashouryo** [comment]
Since I am new to shader, I am mainly learning from ShaderToy. This plugin will resolve my browser's performance issue. I am looking forward to use this plugin!

**Comment by dfranx** [comment]
@Kashouryo as promised, here is the plugin that makes loading Shadertoy projects a much easier process: [PluginShadertoy](https://github.com/dfranx/PluginShadertoy)

It doesn't support some features yet (like cubemaps, "audio shaders", etc...) but I will implement those after I finish SHADERed v1.3.

The plugin just converts Shadertoy projects into SHADERed projects. It doesn't try to replicate Shadertoy features because that's not SHADERed's goal and would be pointless in my opinion.

![shadertoy](https://user-images.githubusercontent.com/30801537/71487673-04ec9e80-281d-11ea-8122-36e4056f4215.gif)
