### ISSUE TITLE
`bin/data/settings.ini` should be in .gitignore; a default settings file should be distributed and the user's settings.ini applied after

### ISSUE THREAD

**Issue by ctrlcctrlv** [dfranx/SHADERed#47]
Makes updates harder when new settings are added.

**Comment by dfranx** [comment]
Thanks for the suggestion. Instead of having a file such as `settings.default.ini`, I've completely deleted the `settings.ini` from the repository and added it to `.gitignore` file. 
SHADERed automatically sets everything up anyway, so when `settings.ini` is missing (or just a certain field) it will be set to some default value.
