### ISSUE TITLE
Crashes on start in Manjaro Linux with i3 desktop

### ISSUE THREAD

**Issue by a-day-old-bagel** [dfranx/SHADERed#52]
There's a segfault on line 574 of GUIManager.cpp where it says
`if (needsUpdate[ind])`
I think this is happening on the very first frame or two, and it appears that that needsUpdate is empty at this point, and it's trying to dereference element 0 anyway.
Not sure why this is happening (I haven't fully understood your codebase yet, but I'm working on it). Any ideas?

**Comment by dfranx** [comment]
Hmm.. not sure what causes this right now. Probably my poor handling of concurrency..
Obviously, the quick fix would be to add a simple if that checks the size of `needsUpdate`. But I think it can be fixed in a much better way.
I'll push that quick fix tomorrow... but I plan to refactor and fix some parts of the codebase (there's some really bad parts 😅) in the v1.3.* versions and so I will try to find a "real" fix.

**Comment by dfranx** [comment]
I have just pushed a hotfix.. I will find an actual cause of this problem after I release v1.3.

**Comment by dfranx** [comment]
Forgot to find actual cause, but I've completely reworked how this part of SHADERed works - "auto recompile" feature doesn't use threads anymore (which, if I remember correctly, was what caused this bug?).
