### ISSUE TITLE
Remember interface DPI settings

### ISSUE THREAD

**Issue by hellocatfood** [dfranx/SHADERed#99]
I've compiled Shadered 1.3.4 on Ubuntu 20.04 on a Dell XPS 13 laptop. When I launch the application the interface is scaled too large.

![Screenshot from 2020-06-02 15-16-00](https://user-images.githubusercontent.com/151947/83532373-116cd580-a4e6-11ea-849d-238310626cfa.png)

I can untick the DPI aware button in the options but when I reopen the application the scale is back to being large. Can there be a way to remember the settings?

**Comment by dfranx** [comment]
I've tested this and it should save the UI scale... Are you sure you properly closed SHADERed?
You can also edit the `settings.ini` file directly (edit the "uiscale=" line and make sure "autoscale" is turned off (line above)).

**Comment by hellocatfood** [comment]
I've just tested it again and the UI scale isn't remembered. I tried closing it using alf + f4, File > Exit, and pressing the close button on the window itself. Each time I set the UI scale and each time I reopen it the scale isn't remembered.

Here's a screen recording I did showing this https://youtu.be/R-is_Y298ys

**Comment by dfranx** [comment]
Thank you so much for the screen recording. That changelog window should open only once. It doesn't save the settings and various other info (for example: that it has already shown the changelog window, which is located in a completely different file)...
Which leads me to believe that SHADERed doesn't have write permissions?

It does find the files (because it loads the correct fonts and workspace state), but it seems that it cannot write to them.

**Comment by hellocatfood** [comment]
When I installed I did do `sudo make install` as the final step, so in theory it should have write permissions.

I've just tried compiling and installing again on my other computer (Dell XPS 15 Ubuntu 20.04) and still the same issue occurs.

Where is settings.ini supposed to be located? I've looked in /usr/local/share/shadered and my home folder and nothing is there

**Comment by dfranx** [comment]
I've actually just tested this on my Ubuntu machine too, it happens to me too.. I'll look into this issue later tonight. Sorry for inconvenience and thank you for opening this issue!

**Comment by dfranx** [comment]
The settings.ini should be in `/usr/local/share/shadered` but it is created after the first run (but since SHADERed can't write it isn't created).
Anyway, when running shadered as superuser everything works fine (do "sudo shadered" in terminal).
I guess possible fix could be to also search for such files in user's home directory. I'll try to implement this in v1.3.5

**Comment by dfranx** [comment]
@hellocatfood This should be fixed in the latest commit ( b4397f561abffd0dc3ddc62559086e9a19ff1012 ). Some files should now be located in the `$HOME/.local/share/shadered` directory.

Closing.
